auto_exposure:     True
exposure:          0.009
auto_gain:         True
gain:              1
auto_whitebalance: True
frame_id: high_def_optical_frame
stream_bytes_per_second: 45000000
auto_adjust_stream_bytes_per_second: False
